import type { Metadata } from 'next'
import { Lacquer } from 'next/font/google'
import './_styles/globals.css'
import { ApolloWrapper } from './_components/apolloProvider'
import Image from 'next/image'

const lacquerFont = Lacquer({
  variable: '--font-lacquer',
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${lacquerFont.variable} antialiased`}>
        <ApolloWrapper>
          <Image
            src={'/portrait.webp'}
            alt="image"
            width={852}
            height={938}
            className="portrait-image"
            priority
            loading="eager"
          />
          <div className="container mx-auto">
            <div className="outer">{children}</div>
          </div>
        </ApolloWrapper>
      </body>
    </html>
  )
}
