import type { Metadata } from 'next'
import { Lacquer } from 'next/font/google'
import './globals.css'
import { ApolloWrapper } from './_components/apolloProvider'

const lacquerFont = Lacquer({
  variable: '--font-lacquer',
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${lacquerFont.variable} antialiased`}>
        <ApolloWrapper>
          <div className="container mx-auto py-8">
            <div className="outer">{children}</div>
          </div>
        </ApolloWrapper>
      </body>
    </html>
  )
}
